import { Category } from "../Category";
import { Daraya } from "../Quirks/Hiveswap/Daraya";
import { Stelsa } from "../Quirks/Hiveswap/Stelsa";
import { Kuprum } from "../Quirks/Hiveswap/Kuprum";
import { Baisil } from "../Quirks/Hiveswap/Baizil";
import { Remele } from "../Quirks/Hiveswap/Remele";
import { Bronya } from "../Quirks/Hiveswap/Bronya";
import { Karako } from "../Quirks/Hiveswap/Karako";
import { Polypa } from "../Quirks/Hiveswap/Polypa";
import { Tirona } from "../Quirks/Hiveswap/Tirona";
import { Amisia } from "../Quirks/Hiveswap/Amisia";
import { Lanque } from "../Quirks/Hiveswap/Lanque";
import { Barzum } from "../Quirks/Hiveswap/Barzum";
import { Xefros } from "../Quirks/Hiveswap/Xefros";
import { Folykl } from "../Quirks/Hiveswap/Folykl";
import { Ardata } from "../Quirks/Hiveswap/Ardata";
import { Marsti } from "../Quirks/Hiveswap/Marsti";
import { Azdaja } from "../Quirks/Hiveswap/Azdaja";
import { Zebede } from "../Quirks/Hiveswap/Zebede";
import { Fozzer } from "../Quirks/Hiveswap/Fozzer";
import { Lynera } from "../Quirks/Hiveswap/Lynera";
import { Boldir } from "../Quirks/Hiveswap/Boldir";
import { Vikare } from "../Quirks/Hiveswap/Vikare";
import { Nihkee } from "../Quirks/Hiveswap/Nihkee";
import { Chixie } from "../Quirks/Hiveswap/Chixie";
import { Chahut } from "../Quirks/Hiveswap/Chahut";
import { Wanshi } from "../Quirks/Hiveswap/Wanshi";
import { Mallek } from "../Quirks/Hiveswap/Mallek";
import { Diemen } from "../Quirks/Hiveswap/Diemen";
import { Trizza } from "../Quirks/Hiveswap/Trizza";
import { Tagora } from "../Quirks/Hiveswap/Tagora";
import { Tegiri } from "../Quirks/Hiveswap/Tegiri";
import { Skylla } from "../Quirks/Hiveswap/Skylla";
import { Zebruh } from "../Quirks/Hiveswap/Zebruh";
import { Elwurd } from "../Quirks/Hiveswap/Elwurd";
import { Tyzias } from "../Quirks/Hiveswap/Tyzias";

export class Hiveswap extends Category {
    constructor() {
        super("Hiveswap");

        this.quirks.push(new Xefros());
        this.quirks.push(new Trizza());
        this.quirks.push(new Diemen());
        this.quirks.push(new Ardata());
        this.quirks.push(new Amisia());
        this.quirks.push(new Skylla());
        this.quirks.push(new Bronya());
        this.quirks.push(new Tagora());
        this.quirks.push(new Vikare());
        this.quirks.push(new Polypa());
        this.quirks.push(new Zebruh());
        this.quirks.push(new Elwurd());
        this.quirks.push(new Kuprum());
        this.quirks.push(new Folykl());
        this.quirks.push(new Remele());
        this.quirks.push(new Tyzias());
        this.quirks.push(new Chixie());
        this.quirks.push(new Azdaja());
        this.quirks.push(new Chahut());
        this.quirks.push(new Zebede());
        this.quirks.push(new Tegiri());
        this.quirks.push(new Mallek());
        this.quirks.push(new Lynera());
        this.quirks.push(new Tirona());
        this.quirks.push(new Boldir());
        this.quirks.push(new Stelsa());
        this.quirks.push(new Marsti());
        this.quirks.push(new Karako());
        this.quirks.push(new Wanshi());
        this.quirks.push(new Fozzer());
        this.quirks.push(new Daraya());
        this.quirks.push(new Nihkee());
        this.quirks.push(new Lanque());
        this.quirks.push(new Barzum());
        this.quirks.push(new Baisil());
    }
}