import Category from "quirks/Category";
import Daraya from "quirks/canon/database/hiveswap/Daraya";
import Stelsa from "quirks/canon/database/hiveswap/Stelsa";
import Kuprum from "quirks/canon/database/hiveswap/Kuprum";
import Baizli from "quirks/canon/database/hiveswap/Baizli";
import Remele from "quirks/canon/database/hiveswap/Remele";
import Bronya from "quirks/canon/database/hiveswap/Bronya";
import Karako from "quirks/canon/database/hiveswap/Karako";
import Polypa from "quirks/canon/database/hiveswap/Polypa";
import Tirona from "quirks/canon/database/hiveswap/Tirona";
import Amisia from "quirks/canon/database/hiveswap/Amisia";
import Lanque from "quirks/canon/database/hiveswap/Lanque";
import Barzum from "quirks/canon/database/hiveswap/Barzum";
import Xefros from "quirks/canon/database/hiveswap/Xefros";
import Folykl from "quirks/canon/database/hiveswap/Folykl";
import Ardata from "quirks/canon/database/hiveswap/Ardata";
import Marsti from "quirks/canon/database/hiveswap/Marsti";
import Azdaja from "quirks/canon/database/hiveswap/Azdaja";
import Zebede from "quirks/canon/database/hiveswap/Zebede";
import Fozzer from "quirks/canon/database/hiveswap/Fozzer";
import Lynera from "quirks/canon/database/hiveswap/Lynera";
import Boldir from "quirks/canon/database/hiveswap/Boldir";
import Vikare from "quirks/canon/database/hiveswap/Vikare";
import Nihkee from "quirks/canon/database/hiveswap/Nihkee";
import Chixie from "quirks/canon/database/hiveswap/Chixie";
import Chahut from "quirks/canon/database/hiveswap/Chahut";
import Wanshi from "quirks/canon/database/hiveswap/Wanshi";
import Mallek from "quirks/canon/database/hiveswap/Mallek";
import Diemen from "quirks/canon/database/hiveswap/Diemen";
import Trizza from "quirks/canon/database/hiveswap/Trizza";
import Tagora from "quirks/canon/database/hiveswap/Tagora";
import Tegiri from "quirks/canon/database/hiveswap/Tegiri";
import Skylla from "quirks/canon/database/hiveswap/Skylla";
import Zebruh from "quirks/canon/database/hiveswap/Zebruh";
import Elwurd from "quirks/canon/database/hiveswap/Elwurd";
import Tyzias from "quirks/canon/database/hiveswap/Tyzias";
import Cirava from "quirks/canon/database/hiveswap/Cirava";
import Marvus from "quirks/canon/database/hiveswap/Marvus";

export default class Hiveswap extends Category {
    public constructor() {
        super("Hiveswap");

        this.addQuirk(new Xefros());
        this.addQuirk(new Trizza());
        this.addQuirk(new Diemen());
        this.addQuirk(new Ardata());
        this.addQuirk(new Cirava());
        this.addQuirk(new Amisia());
        this.addQuirk(new Skylla());
        this.addQuirk(new Bronya());
        this.addQuirk(new Tagora());
        this.addQuirk(new Vikare());
        this.addQuirk(new Polypa());
        this.addQuirk(new Zebruh());
        this.addQuirk(new Elwurd());
        this.addQuirk(new Kuprum());
        this.addQuirk(new Folykl());
        this.addQuirk(new Remele());
        this.addQuirk(new Tyzias());
        this.addQuirk(new Chixie());
        this.addQuirk(new Azdaja());
        this.addQuirk(new Chahut());
        this.addQuirk(new Zebede());
        this.addQuirk(new Tegiri());
        this.addQuirk(new Mallek());
        this.addQuirk(new Lynera());
        this.addQuirk(new Tirona());
        this.addQuirk(new Boldir());
        this.addQuirk(new Stelsa());
        this.addQuirk(new Marsti());
        this.addQuirk(new Karako());
        this.addQuirk(new Wanshi());
        this.addQuirk(new Fozzer());
        this.addQuirk(new Marvus());
        this.addQuirk(new Daraya());
        this.addQuirk(new Nihkee());
        this.addQuirk(new Lanque());
        this.addQuirk(new Barzum());
        this.addQuirk(new Baizli());
    }
}